name: Node CI

on:
  pull_request:
  # allow manual run
  workflow_dispatch:
  # always run on main
  push:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: yarn install, build, and test
        run: |
          yarn install --immutable
          yarn build
          yarn typecheck
          yarn test
        env:
          CI: true
